name: QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt install cmake
      - name: Setup
        run: cmake -S . -B cmake-build
      - name: Build
        run: cmake --build cmake-build
      - name: Run
        run: ctest --test-dir cmake-build/tests --verbose
