name: QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt install clang-format
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{runner.os}}-pre-commit
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt install cmake
      - name: Setup
        run: cmake -S . -B cmake-build
      - name: Build
        run: cmake --build cmake-build
      - name: Run
        run: ctest --test-dir cmake-build/tests --verbose
